//! Build-time code generation from `languages.toml` (Phase 7.1)

use serde::Deserialize;
use std::collections::{BTreeMap, HashMap};
use std::env;
use std::fs;
use std::path::Path;

#[derive(Debug, Deserialize)]
struct LanguagesFile {
    languages: BTreeMap<String, LanguageEntry>,
    bundles: BTreeMap<String, BundleEntry>,
}

#[derive(Debug, Deserialize)]
struct LanguageEntry {
    handler: String,
    #[serde(default)]
    plugin: Option<String>,
    #[serde(default)]
    module: Option<String>,
    #[serde(rename = "crate", default)]
    crate_field: String,
    /// Grammar loader: `language` (default) or `LANGUAGE` (tree-sitter-language crates)
    #[serde(default = "default_grammar_export")]
    grammar_export: String,
    extensions: Vec<String>,
    #[serde(default)]
    function_kinds: Vec<String>,
    #[serde(default)]
    class_kinds: Vec<String>,
    #[serde(default)]
    regex_patterns: Vec<RegexPattern>,
    #[serde(default = "default_true")]
    enable_complexity: bool,
    #[serde(default)]
    enable_type_inference: bool,
}

fn default_true() -> bool {
    true
}

fn default_grammar_export() -> String {
    "language".to_string()
}

#[derive(Debug, Deserialize)]
struct RegexPattern {
    pattern: String,
    symbol_type: String,
}

#[derive(Debug, Deserialize)]
struct BundleEntry {
    languages: Vec<String>,
}

fn main() {
    println!("cargo:rerun-if-changed=languages.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let toml_path = Path::new(&manifest_dir).join("languages.toml");
    let content = fs::read_to_string(&toml_path).expect("Failed to read languages.toml");
    let config: LanguagesFile =
        toml::from_str(&content).expect("Failed to parse languages.toml");

    validate(&config);

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(
        Path::new(&out_dir).join("generated_register.rs"),
        generate_register(&config),
    )
    .expect("Failed to write generated_register.rs");
    fs::write(
        Path::new(&out_dir).join("generated_lang_configs.rs"),
        generate_lang_configs(&config),
    )
    .expect("Failed to write generated_lang_configs.rs");
}

fn validate(config: &LanguagesFile) {
    let mut seen_ext: HashMap<String, String> = HashMap::new();
    for (id, lang) in &config.languages {
        if lang.extensions.is_empty() {
            panic!("Language '{id}' must declare at least one extension");
        }
        for ext in &lang.extensions {
            if let Some(other) = seen_ext.insert(ext.clone(), id.clone()) {
                panic!("Duplicate extension '{ext}' in languages '{other}' and '{id}'");
            }
        }
        match lang.handler.as_str() {
            "custom" => {
                if lang.plugin.is_none() || lang.module.is_none() {
                    panic!("Custom language '{id}' requires plugin and module fields");
                }
            }
            "regex" if lang.regex_patterns.is_empty() => {
                panic!("Regex language '{id}' requires regex_patterns");
            }
            "tree-sitter" if !lang.regex_patterns.is_empty() => {
                // Hybrid: tree-sitter node kinds plus supplemental regex patterns.
            }
            "tree-sitter" | "markdown" | "regex" => {}
            other => panic!("Unknown handler '{other}' for language '{id}'"),
        }
    }

    for (bundle_id, bundle) in &config.bundles {
        for lang in &bundle.languages {
            if !config.languages.contains_key(lang) {
                panic!("Bundle '{bundle_id}' references unknown language '{lang}'");
            }
        }
    }
}

fn feature_name(lang_id: &str) -> String {
    format!("lang-{lang_id}")
}

fn grammar_crate_ident(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}

fn const_name(id: &str) -> String {
    id.to_uppercase().replace('-', "_")
}

fn escape_rust_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn generate_register(config: &LanguagesFile) -> String {
    let mut code = String::from(
        "// Auto-generated by build.rs — DO NOT EDIT\n\n\
         /// Register all language plugins enabled by Cargo features.\n\
         pub(super) fn register_all_language_plugins(registry: &mut LanguageRegistry) {\n",
    );

    for (id, lang) in &config.languages {
        let feature = feature_name(id);
        code.push_str(&format!("    #[cfg(feature = \"{feature}\")]\n    {{\n"));

        match lang.handler.as_str() {
            "custom" => {
                let module = lang.module.as_ref().expect("module");
                let plugin = lang.plugin.as_ref().expect("plugin");
                code.push_str(&format!(
                    "        use {module}::{plugin};\n\
                     registry.register_language_plugin(Arc::new({plugin}::new().expect(\"init {plugin}\")));\n"
                ));
            }
            "regex" => {
                code.push_str(&format!(
                    "        use crate::languages::generic::RegexLanguagePlugin;\n\
                     registry.register_language_plugin(Arc::new(RegexLanguagePlugin::new(\"{id}\").expect(\"init regex {id}\")));\n"
                ));
            }
            "tree-sitter" => {
                let crate_name = if lang.crate_field.is_empty() {
                    format!("tree-sitter-{id}")
                } else {
                    lang.crate_field.clone()
                };
                let crate_ident = grammar_crate_ident(&crate_name);
                let loader_fn = format!("load_{}_grammar", id.replace('-', "_"));
                let loader_body = match lang.grammar_export.as_str() {
                    "language" => format!("{crate_ident}::language()"),
                    "LANGUAGE" => format!("{crate_ident}::LANGUAGE.into()"),
                    symbol => format!("{crate_ident}::{symbol}.into()"),
                };
                code.push_str(&format!(
                    "        fn {loader_fn}() -> tree_sitter::Language {{\n\
                     \t    {loader_body}\n\
                     }}\n\
                     use crate::languages::generic::TreeSitterLanguagePlugin;\n\
                     registry.register_language_plugin(Arc::new(\n\
                         TreeSitterLanguagePlugin::new(\"{id}\", {loader_fn})\n\
                             .expect(\"init tree-sitter {id}\"),\n\
                     ));\n"
                ));
            }
            "markdown" => {
                code.push_str(
                    "        use crate::languages::config::MarkdownPlugin;\n\
                     registry.register_language_plugin(Arc::new(MarkdownPlugin::new().expect(\"init markdown\")));\n",
                );
            }
            other => panic!("Unknown handler: {other}"),
        }

        code.push_str("    }\n\n");
    }

    code.push_str("}\n");
    code
}

fn generate_lang_configs(config: &LanguagesFile) -> String {
    let mut code = String::from("// Auto-generated language configs — DO NOT EDIT\n\n");

    for (id, lang) in &config.languages {
        if !matches!(lang.handler.as_str(), "regex" | "tree-sitter") {
            continue;
        }

        let const_id = const_name(id);
        let exts: Vec<String> = lang
            .extensions
            .iter()
            .map(|e| format!("\"{e}\""))
            .collect();
        let fn_kinds: Vec<String> = lang
            .function_kinds
            .iter()
            .map(|k| format!("\"{k}\""))
            .collect();
        let cls_kinds: Vec<String> = lang
            .class_kinds
            .iter()
            .map(|k| format!("\"{k}\""))
            .collect();

        code.push_str(&format!("static EXT_{const_id}: &[&str] = &[{}];\n", exts.join(", ")));
        code.push_str(&format!(
            "static FN_{const_id}: &[&str] = &[{}];\n",
            if fn_kinds.is_empty() {
                "".to_string()
            } else {
                fn_kinds.join(", ")
            }
        ));
        code.push_str(&format!(
            "static CLS_{const_id}: &[&str] = &[{}];\n",
            if cls_kinds.is_empty() {
                "".to_string()
            } else {
                cls_kinds.join(", ")
            }
        ));

        if !lang.regex_patterns.is_empty() {
            code.push_str(&format!("static RE_{const_id}: &[super::RegexPatternConfig] = &[\n"));
            for pat in &lang.regex_patterns {
                let sym = match pat.symbol_type.as_str() {
                    "function" => "SymbolType::Function",
                    "class" => "SymbolType::Class",
                    "struct" => "SymbolType::Struct",
                    "enum" => "SymbolType::Enum",
                    "interface" => "SymbolType::Interface",
                    "macro" => "SymbolType::Macro",
                    other => panic!("Unknown symbol_type: {other}"),
                };
                code.push_str(&format!(
                    "    super::RegexPatternConfig {{ pattern: \"{}\", symbol_type: crate::languages::plugin_trait::{sym} }},\n",
                    escape_rust_str(&pat.pattern)
                ));
            }
            code.push_str("];\n");
        }

        let regex_patterns_value = if lang.regex_patterns.is_empty() {
            "None".to_string()
        } else {
            format!("Some(RE_{const_id})")
        };

        code.push_str(&format!(
            "pub static CONFIG_{const_id}: super::LanguageConfig = super::LanguageConfig {{\n\
             id: \"{id}\",\n\
             extensions: EXT_{const_id},\n\
             function_kinds: FN_{const_id},\n\
             class_kinds: CLS_{const_id},\n\
             enable_complexity: {},\n\
             enable_type_inference: {},\n\
             regex_patterns: {regex_patterns_value},\n\
         }};\n\n",
            lang.enable_complexity,
            lang.enable_type_inference,
        ));
    }

    code.push_str("pub fn get_language_config(id: &str) -> Option<&'static super::LanguageConfig> {\n");
    code.push_str("    match id {\n");
    for (id, lang) in &config.languages {
        if matches!(lang.handler.as_str(), "regex" | "tree-sitter") {
            code.push_str(&format!(
                "        \"{id}\" => Some(&CONFIG_{}),\n",
                const_name(id)
            ));
        }
    }
    code.push_str("        _ => None,\n    }\n}\n");
    code
}
