//! Git hook templates and installation (Phase 13.2–13.3).

use crate::config::project::RbuilderConfig;
use crate::error::{Error, Result};
use crate::git_util;
use std::fs;
use std::path::{Path, PathBuf};

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

const PRE_COMMIT: &str = r#"#!/bin/sh
# Generated by rbuilder — pre-commit risk check (Phase 13.2)
set -e

STAGED=$(git diff --cached --name-only --diff-filter=ACMR)
if [ -z "$STAGED" ]; then
  exit 0
fi

if ! command -v rbuilder >/dev/null 2>&1; then
  echo "rbuilder not found in PATH; skipping pre-commit hook" >&2
  exit 0
fi

RESULT=$(rbuilder detect-changes --json $STAGED)
RISK=$(echo "$RESULT" | sed -n 's/.*"risk_level": *"\([^"]*\)".*/\1/p' | head -1)

if [ "$RISK" = "CRITICAL" ]; then
  echo "ERROR: Critical risk detected in staged changes!" >&2
  echo "$RESULT" >&2
  echo "" >&2
  echo "Aborting commit. Use 'git commit --no-verify' to bypass." >&2
  exit 1
fi

if [ "$RISK" = "HIGH" ]; then
  echo "WARNING: High risk detected in staged changes." >&2
  echo "$RESULT" >&2
  printf "Continue with commit? (y/N) "
  read -r REPLY
  if [ "$REPLY" != "y" ] && [ "$REPLY" != "Y" ]; then
    exit 1
  fi
fi

exit 0
"#;

const POST_COMMIT: &str = r#"#!/bin/sh
# Generated by rbuilder — post-commit graph update (Phase 13.2)
set -e

if ! command -v rbuilder >/dev/null 2>&1; then
  exit 0
fi

COMMITTED=$(git diff-tree --no-commit-id --name-only -r HEAD)
if [ -z "$COMMITTED" ]; then
  exit 0
fi

echo "Updating knowledge graph..."
rbuilder update --files $COMMITTED
echo "Graph updated."
"#;

const POST_CHECKOUT: &str = r#"#!/bin/sh
# Generated by rbuilder — post-checkout incremental index (Phase 13.3)
# Args: $1=previous HEAD, $2=new HEAD, $3=branch flag (1=branch checkout)
set -e

if [ "$3" != "1" ]; then
  exit 0
fi

if ! command -v rbuilder >/dev/null 2>&1; then
  exit 0
fi

PREV="$1"
CURR="$2"
if [ -z "$PREV" ] || [ -z "$CURR" ] || [ "$PREV" = "$CURR" ]; then
  exit 0
fi

echo "Branch switch detected; updating graph for changed files..."
CHANGED=$(git diff --name-only "$PREV" "$CURR")
if [ -z "$CHANGED" ]; then
  exit 0
fi

rbuilder update --files $CHANGED
echo "Graph updated after branch switch."
"#;

/// Install git hooks into `.git/hooks/`.
pub fn install_hooks(repo_root: &Path, force: bool) -> Result<Vec<PathBuf>> {
    let config = RbuilderConfig::load(repo_root)?;
    let git_dir = git_util::git_dir(repo_root)?;
    let hooks_dir = git_dir.join("hooks");
    fs::create_dir_all(&hooks_dir)
        .map_err(|e| Error::Other(format!("Failed to create hooks dir: {e}")))?;

    let mut written = Vec::new();
    if config.hooks.pre_commit {
        written.push(write_hook(
            &hooks_dir.join("pre-commit"),
            PRE_COMMIT,
            force,
        )?);
    }
    if config.hooks.post_commit {
        written.push(write_hook(
            &hooks_dir.join("post-commit"),
            POST_COMMIT,
            force,
        )?);
    }
    if config.hooks.post_checkout {
        written.push(write_hook(
            &hooks_dir.join("post-checkout"),
            POST_CHECKOUT,
            force,
        )?);
    }

    if !RbuilderConfig::config_path(repo_root).exists() {
        config.save(repo_root)?;
    }

    Ok(written)
}

fn write_hook(path: &Path, content: &str, force: bool) -> Result<PathBuf> {
    if path.exists() && !force {
        return Err(Error::Other(format!(
            "Hook already exists: {} (use --force to overwrite)",
            path.display()
        )));
    }
    fs::write(path, content)
        .map_err(|e| Error::Other(format!("Failed to write {}: {e}", path.display())))?;
    #[cfg(unix)]
    {
        let mut perms = fs::metadata(path)
            .map_err(|e| Error::Other(e.to_string()))?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(path, perms)
            .map_err(|e| Error::Other(format!("Failed to chmod {}: {e}", path.display())))?;
    }
    Ok(path.to_path_buf())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;
    use tempfile::TempDir;

    fn init_git(root: &Path) {
        Command::new("git").args(["init"]).current_dir(root).output().unwrap();
        Command::new("git")
            .args(["config", "user.email", "t@example.com"])
            .current_dir(root)
            .output()
            .unwrap();
        Command::new("git")
            .args(["config", "user.name", "Test"])
            .current_dir(root)
            .output()
            .unwrap();
    }

    #[test]
    fn test_install_hooks() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        init_git(root);
        let hooks = install_hooks(root, true).unwrap();
        assert_eq!(hooks.len(), 3);
        #[cfg(unix)]
        {
            for hook in &hooks {
                let meta = fs::metadata(hook).unwrap();
                assert!(meta.permissions().mode() & 0o111 != 0);
            }
        }
    }
}
