//! Git hook templates and installation.

use crate::git_util;
use rbuilder_error::{Error, Result};
use rbuilder_project_config::project::RbuilderConfig;
use std::fs;
use std::path::{Path, PathBuf};

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

const PRE_COMMIT: &str = r#"#!/bin/sh
# Generated by rbuilder — pre-commit check
set -e

STAGED=$(git diff --cached --name-only --diff-filter=ACMR)
if [ -z "$STAGED" ]; then
  exit 0
fi

if ! command -v rbuilder >/dev/null 2>&1; then
  echo "rbuilder not found in PATH; skipping pre-commit hook" >&2
  exit 0
fi

# Run update to ensure graph is up to date with staged changes
echo "Checking staged changes..." >&2
rbuilder update --files $STAGED 2>&1 | grep -v "^Processed" || true

exit 0
"#;

const POST_COMMIT: &str = r#"#!/bin/sh
# Generated by rbuilder — post-commit graph update
set -e

if ! command -v rbuilder >/dev/null 2>&1; then
  exit 0
fi

COMMITTED=$(git diff-tree --no-commit-id --name-only -r HEAD)
if [ -z "$COMMITTED" ]; then
  exit 0
fi

echo "Updating knowledge graph..."
rbuilder update --files $COMMITTED
echo "Graph updated."
"#;

const POST_CHECKOUT: &str = r#"#!/bin/sh
# Generated by rbuilder — post-checkout incremental index
# Args: $1=previous HEAD, $2=new HEAD, $3=branch flag (1=branch checkout)
set -e

if [ "$3" != "1" ]; then
  exit 0
fi

if ! command -v rbuilder >/dev/null 2>&1; then
  exit 0
fi

PREV="$1"
CURR="$2"
if [ -z "$PREV" ] || [ -z "$CURR" ] || [ "$PREV" = "$CURR" ]; then
  exit 0
fi

echo "Branch switch detected; updating graph for changed files..."
CHANGED=$(git diff --name-only "$PREV" "$CURR")
if [ -z "$CHANGED" ]; then
  exit 0
fi

rbuilder update --files $CHANGED
echo "Graph updated after branch switch."
"#;

/// Install git hooks into `.git/hooks/`.
pub fn install_hooks(repo_root: &Path, force: bool) -> Result<Vec<PathBuf>> {
    let config = RbuilderConfig::load(repo_root)?;
    let git_dir = git_util::git_dir(repo_root)?;
    let hooks_dir = git_dir.join("hooks");
    fs::create_dir_all(&hooks_dir)
        .map_err(|e| Error::Other(format!("Failed to create hooks dir: {e}")))?;

    let mut written = Vec::new();
    if config.hooks.pre_commit {
        written.push(write_hook(
            &hooks_dir.join("pre-commit"),
            PRE_COMMIT,
            force,
        )?);
    }
    if config.hooks.post_commit {
        written.push(write_hook(
            &hooks_dir.join("post-commit"),
            POST_COMMIT,
            force,
        )?);
    }
    if config.hooks.post_checkout {
        written.push(write_hook(
            &hooks_dir.join("post-checkout"),
            POST_CHECKOUT,
            force,
        )?);
    }

    if !RbuilderConfig::config_path(repo_root).exists() {
        config.save(repo_root)?;
    }

    Ok(written)
}

/// Installed hook names and their script bodies (for tests/docs).
pub fn hook_templates() -> Vec<(&'static str, &'static str)> {
    vec![
        ("pre-commit", PRE_COMMIT),
        ("post-commit", POST_COMMIT),
        ("post-checkout", POST_CHECKOUT),
    ]
}

/// Uninstall git hooks from `.git/hooks/`.
pub fn uninstall_hooks(repo_root: &Path) -> Result<()> {
    let git_dir = git_util::git_dir(repo_root)?;
    let hooks_dir = git_dir.join("hooks");

    for (name, _) in hook_templates() {
        let path = hooks_dir.join(name);
        if path.exists() {
            // Only remove if it's our hook (check for rbuilder marker)
            if let Ok(content) = fs::read_to_string(&path) {
                if content.contains("Generated by rbuilder") {
                    fs::remove_file(&path)
                        .map_err(|e| Error::Other(format!("Failed to remove {}: {e}", path.display())))?;
                }
            }
        }
    }

    Ok(())
}

/// List installed git hooks.
pub fn list_hooks(repo_root: &Path) -> Result<Vec<PathBuf>> {
    let git_dir = git_util::git_dir(repo_root)?;
    let hooks_dir = git_dir.join("hooks");

    let mut hooks = Vec::new();
    for (name, _) in hook_templates() {
        let path = hooks_dir.join(name);
        if path.exists() {
            // Check if it's our hook
            if let Ok(content) = fs::read_to_string(&path) {
                if content.contains("Generated by rbuilder") {
                    hooks.push(path);
                }
            }
        }
    }

    Ok(hooks)
}

fn write_hook(path: &Path, content: &str, force: bool) -> Result<PathBuf> {
    if path.exists() && !force {
        return Err(Error::Other(format!(
            "Hook already exists: {} (use --force to overwrite)",
            path.display()
        )));
    }
    fs::write(path, content)
        .map_err(|e| Error::Other(format!("Failed to write {}: {e}", path.display())))?;
    #[cfg(unix)]
    {
        let mut perms = fs::metadata(path)
            .map_err(|e| Error::Other(e.to_string()))?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(path, perms)
            .map_err(|e| Error::Other(format!("Failed to chmod {}: {e}", path.display())))?;
    }
    Ok(path.to_path_buf())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;
    use tempfile::TempDir;

    fn init_git(root: &Path) {
        Command::new("git")
            .args(["init"])
            .current_dir(root)
            .output()
            .unwrap();
        Command::new("git")
            .args(["config", "user.email", "t@example.com"])
            .current_dir(root)
            .output()
            .unwrap();
        Command::new("git")
            .args(["config", "user.name", "Test"])
            .current_dir(root)
            .output()
            .unwrap();
    }

    #[test]
    fn test_install_hooks() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        init_git(root);
        let hooks = install_hooks(root, true).unwrap();
        assert_eq!(hooks.len(), 3);
        #[cfg(unix)]
        {
            for hook in &hooks {
                let meta = fs::metadata(hook).unwrap();
                assert!(meta.permissions().mode() & 0o111 != 0);
            }
        }
    }

    #[test]
    fn test_install_hooks_refuses_existing_without_force() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        init_git(root);
        install_hooks(root, true).unwrap();
        let err = install_hooks(root, false).unwrap_err();
        assert!(err.to_string().contains("already exists"));
    }

    #[test]
    fn test_pre_commit_template_runs_update() {
        let script = hook_templates()
            .into_iter()
            .find(|(name, _)| *name == "pre-commit")
            .map(|(_, body)| body)
            .unwrap();
        assert!(script.contains("rbuilder update --files"));
        assert!(script.contains("STAGED"));
    }

    #[test]
    fn test_post_commit_template_updates_graph() {
        let script = hook_templates()
            .into_iter()
            .find(|(name, _)| *name == "post-commit")
            .map(|(_, body)| body)
            .unwrap();
        assert!(script.contains("rbuilder update --files"));
        assert!(script.contains("diff-tree"));
    }

    #[test]
    fn test_post_checkout_template_branch_switch() {
        let script = hook_templates()
            .into_iter()
            .find(|(name, _)| *name == "post-checkout")
            .map(|(_, body)| body)
            .unwrap();
        assert!(script.contains(r#""$3" != "1""#));
        assert!(script.contains("git diff --name-only"));
        assert!(script.contains("rbuilder update --files"));
    }
}
